import { prisma } from "../src/lib/db";
import type { StoryPageBlockUpsertInput } from "../src/repositories/story-page.repository";

/**
 * STORY-074. Seeds the About page's 23 StoryPageBlock rows — a direct,
 * one-time copy of the literals that used to live in the now-deleted
 * src/lib/story-content.ts (STORY-073). This is the one place those
 * literals still exist as plain data; the storefront reads them from the
 * database from here on, never from a parallel hardcoded module.
 */
const ABOUT_BLOCKS: StoryPageBlockUpsertInput[] = [
  {
    blockKey: "hero",
    blockType: "Hero",
    sortOrder: 0,
    eyebrow: "Our Story",
    title: "A Taste of Sri Lanka, Crafted for the World.",
    body: "Rooted in Sri Lanka's rich culinary traditions, ORISTOR brings authentic flavours, time-honoured recipes and carefully selected ingredients to kitchens around the world.",
    imageUrl: "/images/products/export/curry-powder.webp",
    imageAlt: "Real Oristor curry powder, close up",
  },
  {
    blockKey: "the-land",
    blockType: "Chapter",
    sortOrder: 0,
    eyebrow: "Chapter 01",
    title: "Born from Sri Lanka",
    body: "Our story begins in Sri Lanka — an island where food is deeply connected to culture, family and tradition.",
    imageUrl: "/images/products/export/turmeric-powder.webp",
    imageAlt: "Real Oristor turmeric powder",
    align: "Left",
  },
  {
    blockKey: "tradition-in-every-recipe",
    blockType: "Chapter",
    sortOrder: 1,
    eyebrow: "Chapter 03",
    title: "Recipes With a Memory",
    body: "Some flavours are more than recipes. They are memories passed from one generation to another.",
    imageUrl: "/images/products/best-sellers/Mango-Pickle-Large.webp",
    imageAlt: "Real Oristor mango pickle",
    align: "Right",
  },
  {
    blockKey: "from-tradition-to-the-oristor",
    blockType: "Chapter",
    sortOrder: 2,
    eyebrow: "Chapter 04",
    title: "From Our Kitchen to Yours",
    body: "Our vision is to become the world's most trusted digital destination for authentic Sri Lankan food. Our mission is to enable Oristor to expand globally while preserving Sri Lankan food heritage — through premium products, authentic heritage, and a digital experience built to compete with the world's best food brands.",
    imageUrl: "/images/products/best-sellers/Chili-Paste-Large.png",
    imageAlt: "Real Oristor chilli paste",
    align: "Left",
  },
  {
    blockKey: "quality-and-trust",
    blockType: "Chapter",
    sortOrder: 3,
    eyebrow: "Craftsmanship",
    title: "From Ingredient to Finished Product",
    body: "Every Oristor product follows the same path: real ingredients, careful preparation, and packaging built to protect the flavour inside — the same standard whether a jar is headed to a kitchen down the road or across the world.",
    imageUrl: "/images/products/export/chili-powder.webp",
    imageAlt: "Real Oristor chilli powder",
    align: "Right",
  },
  {
    blockKey: "ingredient-chilli",
    blockType: "IngredientItem",
    sortOrder: 0,
    title: "Chilli",
    body: "The heart of Sri Lankan heat.",
    imageUrl: "/images/products/export/chili-piece.webp",
    imageAlt: "Real Oristor chilli",
  },
  {
    blockKey: "ingredient-mango",
    blockType: "IngredientItem",
    sortOrder: 1,
    title: "Mango",
    body: "Sweet, sour and unmistakably Sri Lankan.",
    imageUrl: "/images/products/best-sellers/Mango-Pickle-Large.webp",
    imageAlt: "Real Oristor mango pickle",
  },
  {
    blockKey: "ingredient-spices",
    blockType: "IngredientItem",
    sortOrder: 2,
    title: "Spices",
    body: "The foundation of our flavour.",
    imageUrl: "/images/products/export/pepper.webp",
    imageAlt: "Real Oristor pepper",
  },
  {
    blockKey: "category-pickles",
    blockType: "ProductCategoryItem",
    sortOrder: 0,
    title: "Pickles",
    body: "Mango, tempered with mustard and chilli.",
    imageUrl: "/images/products/best-sellers/Mango-Pickle-Large.webp",
    imageAlt: "Real Oristor mango pickle",
  },
  {
    blockKey: "category-pickled-vegetables",
    blockType: "ProductCategoryItem",
    sortOrder: 1,
    title: "Pickled Vegetables",
    body: "Jackfruit, banana blossom, lotus — preserved the traditional way.",
    imageUrl: "/images/products/export/oristor-brine-in-Jackfruit-1.webp",
    imageAlt: "Real Oristor jackfruit in brine",
  },
  {
    blockKey: "category-chilli-pastes",
    blockType: "ProductCategoryItem",
    sortOrder: 2,
    title: "Chilli Pastes",
    body: "Built for heat, built for flavour.",
    imageUrl: "/images/products/best-sellers/Chili-Paste-Large.png",
    imageAlt: "Real Oristor chilli paste",
  },
  {
    blockKey: "category-seafood",
    blockType: "ProductCategoryItem",
    sortOrder: 3,
    title: "Seafood",
    body: "Dried, salted, sun-true to the coast.",
    imageUrl: "/images/products/best-sellers/Sprats-Large.webp",
    imageAlt: "Real Oristor dried sprats",
  },
  {
    blockKey: "category-masalas",
    blockType: "ProductCategoryItem",
    sortOrder: 4,
    title: "Masalas",
    body: "Blended for chicken, fish, and everything between.",
    imageUrl: "/images/products/export/chicken-masala.png",
    imageAlt: "Real Oristor chicken masala",
  },
  {
    blockKey: "category-spices",
    blockType: "ProductCategoryItem",
    sortOrder: 5,
    title: "Spices",
    body: "The foundation of every Oristor kitchen.",
    imageUrl: "/images/products/export/curry-powder.webp",
    imageAlt: "Real Oristor curry powder",
  },
  {
    blockKey: "value-o-originality",
    blockType: "ValueItem",
    sortOrder: 0,
    letter: "O",
    title: "Originality",
    body: "Authentic Sri Lankan flavours from time-honoured recipes.",
  },
  {
    blockKey: "value-r-reliability",
    blockType: "ValueItem",
    sortOrder: 1,
    letter: "R",
    title: "Reliability",
    body: "Consistent quality and trust in every product.",
  },
  {
    blockKey: "value-i-innovation",
    blockType: "ValueItem",
    sortOrder: 2,
    letter: "I",
    title: "Innovation",
    body: "Continuously refining and enhancing our offerings.",
  },
  {
    blockKey: "value-s-sustainability",
    blockType: "ValueItem",
    sortOrder: 3,
    letter: "S",
    title: "Sustainability",
    body: "Responsible sourcing and eco-friendly practices.",
  },
  {
    blockKey: "value-t-tradition",
    blockType: "ValueItem",
    sortOrder: 4,
    letter: "T",
    title: "Tradition",
    body: "Honouring Sri Lanka's rich culinary heritage.",
  },
  {
    blockKey: "value-o-outstanding-quality",
    blockType: "ValueItem",
    sortOrder: 5,
    letter: "O",
    title: "Outstanding Quality",
    body: "The highest standards in ingredients and production.",
  },
  {
    blockKey: "value-r-respect",
    blockType: "ValueItem",
    sortOrder: 6,
    letter: "R",
    title: "Respect",
    body: "Valuing customers, suppliers and ethical business practices.",
  },
  {
    blockKey: "global-journey",
    blockType: "GlobalJourney",
    sortOrder: 0,
    title: "From Sri Lanka to the World",
    body: "Our ambition is to share the distinctive flavours of Sri Lanka with kitchens around the world — from the Sri Lankan diaspora to importers, supermarkets, distributors, restaurants and hotels across international markets.",
    ctaLabel: "Explore Our Export Range →",
    ctaHref: "/export",
  },
  {
    blockKey: "cta",
    blockType: "Cta",
    sortOrder: 0,
    title: "Feel the Difference",
    body: "Authentic Sri Lankan flavour. Crafted with care. Made to be shared.",
    ctaLabel: "Explore Products",
    ctaHref: "/products",
    secondaryCtaLabel: "Meet The Oristor",
    secondaryCtaHref: "/contact-us",
  },
];

export async function seedStoryPages() {
  await prisma.$transaction(
    ABOUT_BLOCKS.map((block) =>
      prisma.storyPageBlock.upsert({
        where: { page_blockKey: { page: "AboutUs", blockKey: block.blockKey } },
        create: { page: "AboutUs", ...block },
        update: block,
      }),
    ),
  );
  return { aboutUsBlocks: ABOUT_BLOCKS.length };
}
