import type { RecipeDifficulty, RecipeStatus } from "../src/generated/prisma/client";
import * as recipeRepository from "../src/repositories/recipe.repository";
import { createRecipe } from "../src/services/recipe.service";

// Recipe Centre demo content (STORY-017). tests/e2e/recipe-centre.spec.ts
// depends on these exact values. Hero images reuse Oristor product photos
// until real recipe photography is uploaded through the Media Library.

const categories = [
  { slug: "curries", name: "Curries" },
  { slug: "rice-grains", name: "Rice & Grains" },
  { slug: "sweets-desserts", name: "Sweets & Desserts" },
  { slug: "beverages", name: "Beverages" },
  { slug: "snacks", name: "Snacks" },
  { slug: "sambols-condiments", name: "Sambols & Condiments" },
] as const;

const dietaryTags = [
  { slug: "vegetarian", name: "Vegetarian" },
  { slug: "vegan", name: "Vegan" },
  { slug: "gluten-free", name: "Gluten-Free" },
  { slug: "dairy-free", name: "Dairy-Free" },
  { slug: "nut-free", name: "Nut-Free" },
  { slug: "spicy", name: "Spicy" },
] as const;

type CategorySlug = (typeof categories)[number]["slug"];
type DietarySlug = (typeof dietaryTags)[number]["slug"];

interface SeedRecipe {
  slug: string;
  title: string;
  shortDescription: string;
  heroImage: string;
  heroImageAlt: string;
  category: CategorySlug;
  cuisine: string;
  difficulty: RecipeDifficulty;
  prep: number;
  cook: number;
  servings: number;
  tags: DietarySlug[];
  status: RecipeStatus;
  isFeatured: boolean;
  viewCount: number;
  avgRating: number | null;
  ratingCount: number;
  publishedAt: string | null;
}

const recipes: SeedRecipe[] = [
  {
    slug: "chili-paste-deviled-prawns",
    title: "Chili Paste Deviled Prawns",
    shortDescription: "Juicy prawns tossed with onions, capsicum and Oristor chili paste in a sticky, fiery sauce.",
    heroImage: "/images/products/best-sellers/Chili-Paste-Large.png",
    heroImageAlt: "Oristor stemless chili paste, used in this recipe",
    category: "curries",
    cuisine: "Sri Lankan Chinese",
    difficulty: "Medium",
    prep: 10,
    cook: 15,
    servings: 4,
    tags: ["gluten-free", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: true,
    viewCount: 1840,
    avgRating: 4.7,
    ratingCount: 32,
    publishedAt: "2026-09-01",
  },
  {
    slug: "coconut-sambol-maldive-fish",
    title: "Coconut Sambol with Maldive Fish",
    shortDescription: "Freshly grated coconut pounded with chilli, lime, red onion and Maldive fish. Ready in minutes.",
    heroImage: "/images/products/best-sellers/Maldives-Large.webp",
    heroImageAlt: "Oristor Maldive fish flakes, used in this recipe",
    category: "sambols-condiments",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 10,
    cook: 0,
    servings: 4,
    tags: ["gluten-free", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: true,
    viewCount: 2210,
    avgRating: 4.8,
    ratingCount: 41,
    publishedAt: "2026-08-20",
  },
  {
    slug: "spiced-mango-pickle-rice",
    title: "Spiced Mango Pickle Rice",
    shortDescription: "Fragrant basmati rice stirred through with Oristor mango pickle, curry leaves and mustard seeds.",
    heroImage: "/images/products/best-sellers/Mango-Pickle-Large.webp",
    heroImageAlt: "Oristor mango pickle, used in this recipe",
    category: "rice-grains",
    cuisine: "Fusion",
    difficulty: "Medium",
    prep: 10,
    cook: 25,
    servings: 4,
    tags: ["vegetarian", "vegan", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: true,
    viewCount: 960,
    avgRating: 4.5,
    ratingCount: 12,
    publishedAt: "2026-09-10",
  },
  {
    slug: "sri-lankan-chicken-curry",
    title: "Sri Lankan Chicken Curry",
    shortDescription: "A rich, dark-roasted chicken curry simmered in coconut milk with Oristor chicken masala.",
    heroImage: "/images/products/export/chicken-masala.png",
    heroImageAlt: "Oristor chicken masala, used in this recipe",
    category: "curries",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 15,
    cook: 45,
    servings: 6,
    tags: ["gluten-free", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: true,
    viewCount: 3120,
    avgRating: 4.9,
    ratingCount: 58,
    publishedAt: "2026-07-15",
  },
  {
    slug: "dhal-curry-parippu",
    title: "Dhal Curry (Parippu)",
    shortDescription: "Creamy red lentils cooked with turmeric and coconut milk, finished with mustard seeds and curry leaves.",
    heroImage: "/images/products/export/turmeric-powder.webp",
    heroImageAlt: "Oristor turmeric powder, used in this recipe",
    category: "curries",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 5,
    cook: 25,
    servings: 4,
    tags: ["vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 2650,
    avgRating: 4.6,
    ratingCount: 47,
    publishedAt: "2026-06-30",
  },
  {
    slug: "kiribath-milk-rice",
    title: "Kiribath (Milk Rice)",
    shortDescription: "Traditional coconut milk rice cut into diamonds, served for celebrations with spicy lunu miris.",
    heroImage: "/images/products/export/chili-piece.webp",
    heroImageAlt: "Oristor chili pieces, used in the lunu miris served with this recipe",
    category: "rice-grains",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 5,
    cook: 25,
    servings: 6,
    tags: ["vegetarian", "gluten-free", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 1400,
    avgRating: null,
    ratingCount: 0,
    publishedAt: "2026-04-20",
  },
  {
    slug: "watalappan",
    title: "Watalappan",
    shortDescription: "A silky steamed custard of coconut milk, eggs and kithul jaggery, spiced with cardamom and nutmeg.",
    heroImage: "/images/products/export/Kithul-Jaggery-500g.png",
    heroImageAlt: "Oristor kithul jaggery, used in this recipe",
    category: "sweets-desserts",
    cuisine: "Sri Lankan",
    difficulty: "Hard",
    prep: 20,
    cook: 50,
    servings: 8,
    tags: ["vegetarian", "gluten-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 880,
    avgRating: 4.4,
    ratingCount: 9,
    publishedAt: "2026-05-12",
  },
  {
    slug: "fish-ambul-thiyal",
    title: "Fish Ambul Thiyal",
    shortDescription: "Southern-style sour fish curry, slow-cooked dry with goraka and black pepper until deeply flavoured.",
    heroImage: "/images/products/export/fish-masala.png",
    heroImageAlt: "Oristor fish masala, used in this recipe",
    category: "curries",
    cuisine: "Sri Lankan",
    difficulty: "Hard",
    prep: 20,
    cook: 70,
    servings: 4,
    tags: ["gluten-free", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: false,
    viewCount: 1210,
    avgRating: 4.7,
    ratingCount: 15,
    publishedAt: "2026-08-05",
  },
  {
    slug: "pol-roti-lunu-miris",
    title: "Pol Roti with Lunu Miris",
    shortDescription: "Soft coconut flatbreads cooked on a hot griddle, served with lunu miris, a fiery onion and chilli relish.",
    heroImage: "/images/products/export/chili-powder.webp",
    heroImageAlt: "Oristor chili powder, used in this recipe",
    category: "rice-grains",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 10,
    cook: 5,
    servings: 4,
    tags: ["vegetarian", "vegan", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: false,
    viewCount: 1730,
    avgRating: null,
    ratingCount: 0,
    publishedAt: "2026-09-15",
  },
  {
    slug: "chicken-kottu-roti",
    title: "Chicken Kottu Roti",
    shortDescription: "Chopped godamba roti stir-fried on a hot plate with chicken, egg, vegetables and curry spices.",
    heroImage: "/images/products/export/curry-powder.webp",
    heroImageAlt: "Oristor curry powder, used in this recipe",
    category: "rice-grains",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 15,
    cook: 20,
    servings: 2,
    tags: ["dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: false,
    viewCount: 2980,
    avgRating: 4.6,
    ratingCount: 36,
    publishedAt: "2026-09-18",
  },
  {
    slug: "sri-lankan-ginger-tea",
    title: "Sri Lankan Ginger Tea",
    shortDescription: "Strong Ceylon tea brewed with fresh ginger and a pinch of black pepper, sweetened with jaggery.",
    heroImage: "/images/products/export/pepper.webp",
    heroImageAlt: "Oristor black pepper, used in this recipe",
    category: "beverages",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 2,
    cook: 8,
    servings: 2,
    tags: ["vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 640,
    avgRating: 4.2,
    ratingCount: 5,
    publishedAt: "2026-04-02",
  },
  {
    slug: "wood-apple-juice",
    title: "Wood Apple Juice",
    shortDescription: "A cooling drink of ripe wood apple pulp blended with coconut milk and kithul treacle.",
    heroImage: "/images/products/export/KithulBottle2.png",
    heroImageAlt: "Oristor kithul treacle, used in this recipe",
    category: "beverages",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 10,
    cook: 0,
    servings: 2,
    tags: ["vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 410,
    avgRating: null,
    ratingCount: 0,
    publishedAt: "2026-03-18",
  },
  {
    slug: "vegetable-samosas",
    title: "Vegetable Samosas",
    shortDescription: "Crisp pastry parcels filled with spiced potato, carrot and leeks, fried until golden.",
    heroImage: "/images/products/misc/Masala.webp",
    heroImageAlt: "Oristor masala blend, used in this recipe",
    category: "snacks",
    cuisine: "Sri Lankan",
    difficulty: "Hard",
    prep: 30,
    cook: 20,
    servings: 6,
    tags: ["vegetarian", "vegan", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 1520,
    avgRating: 4.3,
    ratingCount: 21,
    publishedAt: "2026-07-01",
  },
  {
    slug: "seeni-sambol",
    title: "Seeni Sambol",
    shortDescription: "Onions slow-cooked until jammy with chilli, tamarind and a touch of sugar. Sweet, sour and hot.",
    heroImage: "/images/products/domestic/Chili-Paste-Small.webp",
    heroImageAlt: "Oristor chili paste, used in this recipe",
    category: "sambols-condiments",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 10,
    cook: 35,
    servings: 6,
    tags: ["gluten-free", "dairy-free", "nut-free", "spicy"],
    status: "Published",
    isFeatured: false,
    viewCount: 1980,
    avgRating: 4.8,
    ratingCount: 29,
    publishedAt: "2026-06-10",
  },
  {
    slug: "brinjal-moju",
    title: "Brinjal Moju",
    shortDescription: "Fried aubergine pickled with mustard, vinegar, shallots and green chillies. Keeps for days.",
    heroImage: "/images/products/misc/Mango-Pickle-Large.webp",
    heroImageAlt: "Oristor mango pickle, served with this recipe",
    category: "sambols-condiments",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 15,
    cook: 25,
    servings: 6,
    tags: ["vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free"],
    status: "Published",
    isFeatured: false,
    viewCount: 1130,
    avgRating: 4.5,
    ratingCount: 14,
    publishedAt: "2026-05-25",
  },
  {
    slug: "isso-vadai",
    title: "Isso Vadai (Prawn Fritters)",
    shortDescription: "Crunchy lentil fritters topped with whole prawns, a Galle Face street-food favourite.",
    heroImage: "/images/products/best-sellers/Koonisso-Large.webp",
    heroImageAlt: "Oristor koonisso (dried shrimp), used in this recipe",
    category: "snacks",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 20,
    cook: 15,
    servings: 4,
    tags: ["gluten-free", "dairy-free", "spicy"],
    status: "Published",
    isFeatured: false,
    viewCount: 1760,
    avgRating: 4.6,
    ratingCount: 19,
    publishedAt: "2026-08-28",
  },
  // Not Published: must never appear on the storefront. The Draft is flagged
  // featured on purpose (the homepage must still skip it).
  {
    slug: "pumpkin-curry",
    title: "Pumpkin Curry",
    shortDescription: "Sweet pumpkin simmered in coconut milk with roasted curry powder and mustard seeds.",
    heroImage: "/images/products/export/curry-powder.webp",
    heroImageAlt: "Oristor curry powder, used in this recipe",
    category: "curries",
    cuisine: "Sri Lankan",
    difficulty: "Easy",
    prep: 10,
    cook: 20,
    servings: 4,
    tags: ["vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free"],
    status: "Draft",
    isFeatured: true,
    viewCount: 0,
    avgRating: null,
    ratingCount: 0,
    publishedAt: null,
  },
  {
    slug: "milk-toffee",
    title: "Milk Toffee",
    shortDescription: "Condensed milk and sugar cooked to a fudge-like set, flavoured with cardamom and cashew.",
    heroImage: "/images/products/export/Kithul-Jaggery-500g.png",
    heroImageAlt: "Oristor kithul jaggery, used in this recipe",
    category: "sweets-desserts",
    cuisine: "Sri Lankan",
    difficulty: "Medium",
    prep: 5,
    cook: 40,
    servings: 12,
    tags: ["vegetarian", "gluten-free"],
    status: "Archived",
    isFeatured: false,
    viewCount: 900,
    avgRating: 4.1,
    ratingCount: 7,
    publishedAt: "2025-12-01",
  },
];

function requireId(map: Map<string, string>, slug: string): string {
  const id = map.get(slug);
  if (!id) {
    throw new Error(`Unknown seed slug: ${slug}`);
  }
  return id;
}

export async function seedRecipes(): Promise<{ recipes: number; published: number }> {
  const categoryIds = new Map<string, string>();
  for (const [index, category] of categories.entries()) {
    const created = await recipeRepository.createRecipeCategory({ ...category, sortOrder: index + 1 });
    categoryIds.set(category.slug, created.id);
  }

  const tagIds = new Map<string, string>();
  for (const [index, tag] of dietaryTags.entries()) {
    const created = await recipeRepository.createDietaryTag({ ...tag, sortOrder: index + 1 });
    tagIds.set(tag.slug, created.id);
  }

  for (const recipe of recipes) {
    await createRecipe({
      slug: recipe.slug,
      title: recipe.title,
      shortDescription: recipe.shortDescription,
      heroImage: recipe.heroImage,
      heroImageAlt: recipe.heroImageAlt,
      categoryId: requireId(categoryIds, recipe.category),
      cuisine: recipe.cuisine,
      difficulty: recipe.difficulty,
      prepTimeMinutes: recipe.prep,
      cookTimeMinutes: recipe.cook,
      servings: recipe.servings,
      status: recipe.status,
      isFeatured: recipe.isFeatured,
      viewCount: recipe.viewCount,
      avgRating: recipe.avgRating,
      ratingCount: recipe.ratingCount,
      publishedAt: recipe.publishedAt ? new Date(`${recipe.publishedAt}T09:00:00Z`) : null,
      dietaryTagIds: recipe.tags.map((slug) => requireId(tagIds, slug)),
    });
  }

  return { recipes: recipes.length, published: recipes.filter((recipe) => recipe.status === "Published").length };
}
